version: "3.7"

services:
  agibank-test: 
    build:
      context: .
      dockerfile: .Dockerfile
    ports: 
      - "3000:3000"
    networks: 
      - teste-network
    container_name: agibank-test

networks: 
  teste-network:
    driver: bridge
